import { Tag } from "lucide-react";
import { start } from "repl";

export type TipoConteudo = "todos" | "anime" | "filme" | "serie";

export const rankingLista = [
  {
    title: "Uzumaki",
    type: "anime",
    Temporada: "1",
    Idade: "16",
    episodes: 4,
    Image: "/anime/uzumaki.jpg",
    startDate: "",
    lastDate: "",
    postedDays: 2024,
    generos: ["Terror", "Suspense", "Mistério"],
    NotaGugu: 5.5,
    NotaMika: 5,
    synopsis:
      "Ekirie tenta escapar de sua cidade, Kurouzu-cho, onde os moradores ficam obcecados por espirais devido a uma maldição inexplicável.",
  },

  {
    title: "Akame ga Kill",
    type: "anime",
    Temporada: "1",
    Idade: "18",
    episodes: 24,
    Image: "/anime/akamegakill.jpg",
    startDate: "",
    lastDate: "",
    postedDays: 2014,
    generos: ["Ação", "Fantasia", "Drama"],
    checked: true,
    Badge: "verificado",
    NotaGugu: 7.5,
    NotaMika: 7.5,
    synopsis:
      "O jovem Tatsumi viaja para a capital do Império e acaba se envolvendo com a Night Raid, um grupo de assassinos que luta contra a corrupção do governo.",
  },

  {
    title: "You",
    type: "serie",
    Temporada: "1",
    Idade: "18",
    episodes: 10,
    Image: "/serie/you.jpg",
    startDate: "",
    lastDate: "",
    postedDays: 2018,
    generos: ["Drama", "Suspense", "Romance"],
    checked: true,
    Badge: "verificado",
    NotaGugu: 9.5,
    NotaMika: 9,
    synopsis:
      "Série de suspense psicológico que acompanha Joe Goldberg, um homem aparentemente gentil que se torna perigosamente obcecado pelas pessoas que ama.",
  },

  {
    title: "ReLIFE",
    type: "anime",
    Temporada: "1",
    Idade: "14",
    episodes: 17,
    Image: "/anime/relife.jpg",
    startDate: "",
    lastDate: "",
    postedDays: 2016,
    generos: ["Drama", "Romance", "Slice of Life"],
    checked: true,
    Badge: "verificado",
    NotaGugu: 8,
    NotaMika: 8.5,
    synopsis:
      "Arata Kaizaki recebe a chance de refazer a vida ao voltar ao ensino médio por um ano, enfrentando amadurecimento, amizades e escolhas difíceis.",
  },

  {
    title: "Chainsaw Man",
    type: "anime",
    Temporada: "1",
    Idade: "18",
    episodes: 12,
    Image: "/anime/chainsawman.jpg",
    startDate: "",
    lastDate: "",
    postedDays: 2022,
    generos: ["Ação", "Terror", "Fantasia"],
    checked: true,
    Badge: "verificado",
    NotaGugu: 9,
    NotaMika: 8,
    synopsis:
      "Denji se funde ao demônio Pochita e passa a caçar demônios como uma arma humana em um mundo violento e cruel.",
  },

  {
    title: "Grand Blue",
    type: "anime",
    Temporada: "1",
    Idade: "16",
    episodes: 12,
    Image: "/anime/grandblue.jpg",
    startDate: "",
    lastDate: "",
    postedDays: 2018,
    generos: ["Comédia", "Slice of Life"],
    NotaGugu: 7.5,
    NotaMika: 8.5,
    synopsis:
      "Iori Kitahara entra para um clube de mergulho e acaba vivendo situações caóticas cheias de festas, exageros e amizade.",
  },
  {
    title: "Cyberpunk Edgerunners",
    type: "anime",
    Temporada: "1",
    Idade: "18",
    episodes: 10,
    Image: "/anime/cyberpunk.jpg",
    startDate: "",
    lastDate: "",
    postedDays: 2022,
    generos: ["Ação", "Ficção Científica", "Drama"],
    checked: true,
    Badge: "verificado",
    NotaGugu: 10,
    NotaMika: 9,
    synopsis:
      "David Martinez tenta sobreviver em Night City e se envolve com mercenários em uma história trágica sobre ambição, perda e humanidade.",
  },

  {
    title: "Extermínio 2",
    type: "filme",
    Idade: "18",
    duration: "100min",
    Image: "/filme/exterminio2.jpg",
    startDate: "",
    lastDate: "",
    postedDays: 2007,
    generos: ["Terror", "Suspense", "Ação"],
    checked: true,
    Badge: "verificado",
    NotaGugu: 7.5,
    NotaMika: 7,
    synopsis:
      "Após o suposto controle do vírus da raiva, uma falha humana provoca um novo surto que mergulha Londres novamente no caos.",
  },

  {
    title: "Metal Lords",
    type: "filme",
    Idade: "14",
    duration: "97min",
    Image: "/filme/metallords.jpg",
    startDate: "",
    lastDate: "",
    postedDays: 2022,
    generos: ["Drama", "Comédia", "Música"],
    checked: true,
    Badge: "verificado",
    NotaGugu: 7,
    NotaMika: 9.5,
    synopsis:
      "Dois adolescentes formam uma banda de heavy metal para competir em um festival escolar, lidando com amizade e identidade.",
  },

  {
    title: "O Serviço de Entregas da Kiki",
    type: "filme",
    Idade: "Livre",
    duration: "103min",
    Image: "/filme/kiki.jpg",
    startDate: "",
    lastDate: "",
    postedDays: 1989,
    generos: ["Fantasia", "Slice of Life", "Família"],
    checked: true,
    Badge: "verificado",
    NotaGugu: 6,
    NotaMika: 10,
    synopsis:
      "Kiki, uma jovem bruxa, cria um serviço de entregas enquanto aprende a viver sozinha e a confiar em si mesma.",
  },

  {
    title: "Black Mirror",
    type: "serie",
    Temporada: "6",
    Idade: "16",
    episodes: 33,
    Image: "/serie/blackmirror.jpg",
    startDate: "",
    lastDate: "",
    postedDays: 2011,
    generos: ["Drama", "Ficção Científica", "Suspense"],
    NotaGugu: 8,
    NotaMika: 8,
    synopsis:
      "Série antológica que explora os impactos sombrios da tecnologia na sociedade moderna.",
  },

  {
    title: "Jogo da Morte",
    type: "serie",
    Temporada: "1",
    Idade: "18",
    episodes: 8,
    Image: "/serie/jogodamorte.jpg",
    startDate: "",
    lastDate: "",
    postedDays: 2023,
    generos: ["Drama", "Fantasia", "Suspense"],
    checked: true,
    Badge: "verificado",
    NotaGugu: 6.5,
    NotaMika: 8,
    synopsis:
      "Após tirar a própria vida, um homem é condenado a viver várias mortes em corpos diferentes, refletindo sobre culpa e redenção.",
  },
  {
    title: "Cães de Caça",
    type: "serie",
    Temporada: "1",
    Idade: "18",
    episodes: 8,
    Image: "/serie/caesdecaca.jpg",
    startDate: "",
    lastDate: "",
    postedDays: 2023,
    generos: ["Ação", "Crime", "Drama"],
    checked: true,
    Badge: "verificado",
    NotaGugu: 6,
    NotaMika: 8,
    synopsis:
      "Dois jovens lutadores enfrentam agiotas violentos no submundo do crime, unidos por lealdade e justiça.",
  },

  {
    title: "A Noiva-Cadáver",
    type: "filme",
    Idade: "10",
    duration: "77min",
    Image: "/filme/noivacadaver.jpg",
    startDate: "",
    lastDate: "",
    postedDays: 2005,
    generos: ["Animação", "Fantasia", "Romance"],
    checked: true,
    Badge: "verificado",
    NotaGugu: 7,
    NotaMika: 10,
    synopsis:
      "Victor se vê dividido entre o mundo dos vivos e dos mortos após se casar acidentalmente com uma noiva do além.",
  },

  {
    title: "Premonição 1",
    type: "filme",
    Idade: "16",
    duration: "98min",
    Image: "/filme/premonicao1.jpg",
    startDate: "",
    lastDate: "",
    postedDays: 2000,
    generos: ["Terror", "Suspense"],
    checked: true,
    Badge: "verificado",
    NotaGugu: 8,
    NotaMika: 7,
    synopsis:
      "Um grupo de jovens escapa da morte após uma premonição, mas passa a ser perseguido por um destino inevitável.",
  },

  {
    title: "Premonição 3",
    type: "filme",
    Idade: "16",
    duration: "93min",
    Image: "/filme/premonicao3.jpg",
    startDate: "",
    lastDate: "",
    postedDays: 2006,
    generos: ["Terror", "Suspense"],
    checked: true,
    Badge: "verificado",
    NotaGugu: 8.5,
    NotaMika: 8.5,
    synopsis:
      "Uma adolescente tenta enganar a morte após prever um acidente, mas eventos trágicos seguem um padrão mortal.",
  },

  {
    title: "Premonição 6",
    type: "filme",
    Idade: "18",
    duration: "110min",
    Image: "/filme/premonicao6.jpg",
    startDate: "",
    lastDate: "",
    postedDays: 2025,
    generos: ["Terror", "Suspense"],
    checked: true,
    Badge: "verificado",
    NotaGugu: 8,
    NotaMika: 8,
    synopsis:
      "Uma nova história mostra que interferir no destino pode ter consequências fatais que atravessam gerações.",
  },

  {
    title: "Paranorman",
    type: "filme",
    Idade: "10",
    duration: "92min",
    Image: "/filme/paranorman.jpg",
    startDate: "",
    lastDate: "",
    postedDays: 2012,
    generos: ["Animação", "Fantasia", "Comédia"],
    checked: true,
    Badge: "verificado",
    NotaGugu: 6,
    NotaMika: 9,
    synopsis:
      "Norman, um garoto que fala com os mortos, precisa salvar sua cidade enfrentando fantasmas e preconceitos.",
  },

  {
    title: "Inatividade Paranormal",
    type: "filme",
    Idade: "16",
    duration: "86min",
    Image: "/filme/inatividade1.jpg",
    startDate: "",
    lastDate: "",
    postedDays: 2013,
    generos: ["Comédia", "Paródia", "Terror"],
    checked: true,
    Badge: "verificado",
    NotaGugu: 9.5,
    NotaMika: 9,
    synopsis:
      "Uma paródia de terror que acompanha um casal vivendo eventos sobrenaturais absurdos em sua casa, misturando sustos com humor escrachado.",
  },

  {
    title: "Inatividade Paranormal 2",
    type: "filme",
    Idade: "16",
    duration: "85min",
    Image: "/filme/inatividade2.jpg",
    startDate: "",
    lastDate: "",
    postedDays: 2014,
    generos: ["Comédia", "Paródia", "Terror"],
    checked: true,
    Badge: "verificado",
    NotaGugu: 9,
    NotaMika: 9,
    synopsis:
      "Continuação da paródia que exagera ainda mais os clichês de filmes de terror, com novas situações bizarras e humor irreverente.",
  },

  {
    id: 1,
    title: "Sword Art Online",
    type: "anime",
    Temporada: "4",
    Idade: "14",
    episodes: 96,
    Image: "/anime/swordartonline.jpg",
    startDate: "",
    lastDate: "",
    postedDays: 2012,
    generos: ["Ação", "Fantasia", "Romance"],
    checked: true,
    Badge: "verificado",
    NotaGugu: 9,
    NotaMika: 8.5,
    synopsis:
      "Jogadores ficam presos em um jogo de realidade virtual onde morrer no game significa morrer na vida real, e precisam lutar para escapar.",
  },
  {
    id: 2,
    title: "To Be Hero",
    type: "anime",
    Temporada: "1",
    Idade: "14",
    episodes: 12,
    Image: "/anime/tobehero.jpg",
    startDate: "",
    lastDate: "",
    postedDays: 2016,
    generos: ["Comédia", "Ação", "Drama"],
    checked: true,
    Badge: "verificado",
    NotaGugu: 9.5,
    NotaMika: 8.75,
    synopsis:
      "Um designer fracassado se torna um herói improvável após um evento bizarro, enfrentando monstros enquanto lida com situações absurdas e emocionais.",
  },

  {
    title: "Erased",
    type: "anime",
    Temporada: "1",
    Idade: "14",
    episodes: 12,
    Image: "/anime/erased.jpg",
    startDate: "",
    lastDate: "",
    postedDays: 2016,
    generos: ["Drama", "Suspense", "Mistério"],
    checked: true,
    Badge: "verificado",
    NotaGugu: 10,
    NotaMika: 8.75,
    synopsis:
      "Um homem volta no tempo para sua infância com o objetivo de impedir crimes trágicos e salvar pessoas importantes de seu passado.",
  },

  {
    title: "Uma Fazenda Maluca",
    type: "filme",
    Idade: "Livre",
    duration: "90min",
    Image: "/filme/umafazendamaluca.jpg",
    startDate: "",
    lastDate: "",
    postedDays: 2006,
    generos: ["Animação", "Comédia", "Família"],
    checked: true,
    Badge: "verificado",
    NotaGugu: 1,
    NotaMika: 7,
    synopsis:
      "Animais de uma fazenda vivem situações caóticas e cômicas no dia a dia.",
  },

  {
    title: "[REC] 1",
    type: "filme",
    Idade: "18",
    duration: "78min",
    Image: "/filme/rec1.jpg",
    startDate: "",
    lastDate: "",
    postedDays: 2007,
    generos: ["Terror", "Suspense", "Found Footage"],
    checked: true,
    Badge: "verificado",
    NotaGugu: 8.9,
    NotaMika: 7,
    synopsis:
      "Uma repórter e seu cinegrafista ficam presos em um prédio durante uma quarentena causada por uma infecção aterrorizante.",
  },

  {
    title: "Dandadan",
    type: "anime",
    Temporada: "1",
    Idade: "16",
    episodes: 12,
    Image: "/anime/dandadan.jpg",
    startDate: "",
    lastDate: "",
    postedDays: 2024,
    generos: ["Ação", "Sobrenatural", "Comédia", "Romance"],
    checked: true,
    Badge: "verificado",
    NotaGugu: 7.9,
    NotaMika: 9,
    synopsis:
      "Dois adolescentes se envolvem em batalhas caóticas contra espíritos e alienígenas, misturando ação, humor e romance sobrenatural.",
  },

  {
    title: "O Cemitério das Almas Perdidas",
    type: "filme",
    Idade: "16",
    duration: "95min",
    Image: "/filme/cemiterioalmasperdidas.jpg",
    startDate: "",
    lastDate: "",
    postedDays: 2020,
    generos: ["Terror", "Suspense"],
    checked: true,
    Badge: "verificado",
    NotaGugu: 6.9,
    NotaMika: 5,
    synopsis:
      "Um grupo enfrenta forças malignas ligadas a um antigo cemitério, despertando espíritos e horrores enterrados no passado.",
  },
  {
    title: "Invocação do Mal 4",
    type: "filme",
    Idade: "16",
    duration: "110min",
    Image: "/filme/invocacaodomal4.jpg",
    startDate: "",
    lastDate: "",
    postedDays: 2025,
    generos: ["Terror", "Suspense"],
    checked: true,
    Badge: "verificado",
    NotaGugu: 6,
    NotaMika: 7.5,
    synopsis:
      "Os investigadores paranormais Ed e Lorraine Warren enfrentam um novo caso demoníaco que desafia sua fé e limites.",
  },

  {
    title: "Jackass 4.5",
    type: "filme",
    Idade: "16",
    duration: "96min",
    Image: "/filme/jackass4.jpg",
    startDate: "",
    lastDate: "",
    postedDays: 2022,
    generos: ["Comédia", "Reality", "Ação"],
    checked: true,
    Badge: "verificado",
    NotaGugu: 8,
    NotaMika: 7,
    synopsis:
      "Jackass Forever é uma compilação de acrobacias, esquetes e pegadinhas intercaladas com entrevistas com o elenco no set de filmagem.",
  },

  {
    title: "Ranking of Kings",
    type: "anime",
    Temporada: "1",
    Idade: "12",
    episodes: 23,
    Image: "/anime/rankingofkings.jpg",
    startDate: "",
    lastDate: "",
    postedDays: 2021,
    generos: ["Fantasia", "Aventura", "Drama"],
    checked: true,
    Badge: "verificado",
    NotaGugu: 7.5,
    NotaMika: 8,
    synopsis:
      "Conheça Bojji, um príncipe surdo e impotente que nem sequer pode empunhar a espada de uma criança, mas sonha em se tornar o maior rei do mundo.",
  },

  {
    title: "Hai to Gensou no Grimgar",
    type: "anime",
    Temporada: "1",
    Idade: "14",
    episodes: 12,
    Image: "/anime/grimgar.jpg",
    startDate: "",
    lastDate: "",
    postedDays: 2016,
    generos: ["Fantasia", "Drama", "Aventura"],
    checked: true,
    Badge: "verificado",
    NotaGugu: 8.5,
    NotaMika: 7.5,
    synopsis:
      "Um grupo de jovens acorda em um mundo estilo RPG sem memórias do passado e precisa lutar para sobreviver, enfrentando perdas, fome e a dura realidade de um mundo hostil.",
  },

  {
    title: "Oshi no Ko",
    type: "anime",
    Temporada: "1",
    Idade: "14",
    episodes: 11,
    Image: "/anime/oshinoko.jpg",
    startDate: "",
    lastDate: "",
    postedDays: 2023,
    generos: ["Drama", "Mistério", "Slice of Life"],
    NotaGugu: 9.5,
    NotaMika: 9,
    synopsis:
      "Um médico e sua paciente recém-falecida renascem como gêmeos filhos de uma famosa idol japonesa, vivenciando os bastidores sombrios da indústria do entretenimento.",
  },

  {
    title: "Chainsaw Man: O Filme - Arco da Reze",
    type: "filme",
    Idade: "18",
    duration: "115min",
    Image: "/filme/chainsawmanfilme.jpg",
    startDate: "",
    lastDate: "",
    postedDays: 2025,
    generos: ["Ação", "Terror", "Fantasia Sombria"],
    checked: true,
    Badge: "verificado",
    NotaGugu: 9.5,
    NotaMika: 9,
    synopsis:
      "Denji, um jovem caçador de demônios traído pela yakuza, sobrevive ao se fundir com Pochita. A chegada da misteriosa Reze o leva ao seu confronto mais mortal.",
  },
];
